apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: kong
spec:
  replicas: 2
  selector:
   matchLabels:
    app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        env:
        - name: KONG_PLUGINS
          value: bundled,myheader
        - name: KONG_LUA_PACKAGE_PATH
          value: "/opt/?.lua;;"
        image: papawhiskey93/nodeapp:1.0
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        volumeMounts:
        - name: nodejs-config
          mountPath: /opt/kong/plugins/myheader
      volumes:
      - name: nodejs-config
        configMap:
          name: nodejs-config

